version: '3.4'

services:
  pipelines.api:
    image: ${DOCKER_REGISTRY-}pipelinesapi
    build:
      context: .
      dockerfile: Pipelines.Api/Dockerfile
    depends_on: 
        - mongo
    environment:      
      "MongoDbSettings__ConnectionString": "mongodb://username:password@mongo:27017"
      "MongoDbSettings__DatabaseName": "Pipelines"

  mongo:
    image: mongo
    restart: always
    environment:
     # todo: remove secrets from compose
     MONGO_INITDB_ROOT_USERNAME: username
     MONGO_INITDB_ROOT_PASSWORD: password