version: '3.4'

services:
  back:
    image: ${DOCKER_REGISTRY-}pipelinesapi
    build:
      context: .
      dockerfile: PipelinesApp.Api/Dockerfile
    depends_on: 
        - mongo
    environment:      
      "MongoDbSettings__ConnectionString": "mongodb://username:password@mongo:27017"
      "MongoDbSettings__DatabaseName": "Pipelines"

  front:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    depends_on: 
      - back
    environment:  
      "API_URL": "http://back/api"
    ports:
      - "8082:80"

  migrations:
    image: coldze/mongol
    depends_on: 
      - mongo
    volumes: [
        "./DbMigrations:/DbMigrations"       
      ]
    entrypoint: "mongol migrate --path=/DbMigrations/changelog.json"
    
  mongo:
    image: mongo
    restart: always   
    environment:
     # todo: remove secrets from compose
     MONGO_INITDB_ROOT_USERNAME: username
     MONGO_INITDB_ROOT_PASSWORD: password
    
  mongo-express:
      image: mongo-express
      environment:
          - ME_CONFIG_MONGODB_SERVER=mongo
          - ME_CONFIG_MONGODB_PORT=27017
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_MONGODB_ADMINUSERNAME=username
          - ME_CONFIG_MONGODB_ADMINPASSWORD=password
          - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
          - ME_CONFIG_MONGODB_AUTH_USERNAME=username
          - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
          - ME_CONFIG_BASICAUTH_USERNAME=username
          - ME_CONFIG_BASICAUTH_PASSWORD=password
      depends_on:
          - mongo
      ports:
      - "8083:8081"